// import { Product } from '../../modules/dashboard/models/product';

// export const dummyData: Product[] = [
//   {
//     id: 1,
//     name: 'Product A',
//     description: 'High-quality product for daily use.',
//     imageUrl: 'https://example.com/product-a.jpg',
//     category: 'Electronics',
//     price: 199.99,
//     stock: 100,
//     isActive: true,
//     selected: false,
//     tags: ['tech', 'gadgets'],
//     createdAt: '2024-10-12T12:34:56Z',
//   },
//   {
//     id: 2,
//     name: 'Product B',
//     description: 'Stylish and durable home furniture.',
//     imageUrl: 'https://example.com/product-b.jpg',
//     category: 'Furniture',
//     price: 499.99,
//     stock: 50,
//     isActive: true,
//     selected: false,
//     tags: ['home', 'living'],
//     createdAt: '2024-10-14T12:34:56Z',
//   },
//   {
//     id: 3,
//     name: 'Product C',
//     description: 'Sleek and powerful laptop for professionals.',
//     imageUrl: 'https://example.com/product-c.jpg',
//     category: 'Electronics',
//     price: 1299.99,
//     stock: 20,
//     isActive: false, // Product is not active
//     selected: true,
//     tags: ['laptop', 'computers'],
//     createdAt: '2024-10-16T12:34:56Z',
//   },
//   {
//     id: 4,
//     name: 'Product D',
//     description: 'Comfortable and versatile shoes for all occasions.',
//     imageUrl: 'https://example.com/product-d.jpg',
//     category: 'Footwear',
//     price: 89.99,
//     stock: 150,
//     isActive: true,
//     selected: false,
//     tags: ['fashion', 'comfort'],
//     createdAt: '2024-10-18T12:34:56Z',
//   },
//   {
//     id: 5,
//     name: 'Product E',
//     description: 'Smartphone with cutting-edge features.',
//     imageUrl: 'https://example.com/product-e.jpg',
//     category: 'Electronics',
//     price: 899.99,
//     stock: 30,
//     isActive: true,
//     selected: true,
//     tags: ['smartphone', 'tech'],
//     createdAt: '2024-10-20T12:34:56Z',
//   },
//   {
//     id: 6,
//     name: 'Product F',
//     description: 'Eco-friendly kitchenware for modern homes.',
//     imageUrl: 'https://example.com/product-f.jpg',
//     category: 'Home & Kitchen',
//     price: 39.99,
//     stock: 200,
//     isActive: true,
//     selected: false,
//     tags: ['eco-friendly', 'kitchen'],
//     createdAt: '2024-10-22T12:34:56Z',
//   },
//   {
//     id: 7,
//     name: 'Product G',
//     description: 'Portable speaker with rich sound quality.',
//     imageUrl: 'https://example.com/product-g.jpg',
//     category: 'Electronics',
//     price: 49.99,
//     stock: 120,
//     isActive: true,
//     selected: false,
//     tags: ['audio', 'music'],
//     createdAt: '2024-10-26T12:34:56Z',
//   },
//   {
//     id: 8,
//     name: 'Product H',
//     description: 'Premium wristwatch with classic design.',
//     imageUrl: 'https://example.com/product-h.jpg',
//     category: 'Accessories',
//     price: 299.99,
//     stock: 60,
//     isActive: false, // Product is not active
//     selected: true,
//     tags: ['luxury', 'fashion'],
//     createdAt: '2024-10-28T12:34:56Z',
//   },
// ];
