// import { Task } from "../../modules/dashboard/models/task";

// export const dummyData: Task[] = [
//   {
//     id: 1,
//     title: 'Preparar informe mensual',
//     description: 'Recopilar datos de ventas y preparar un informe detallado.',
//     completed: false,
//     priority: 'high',
//     due_date: '2024-12-31T23:59:59Z',
//     created_at: '2024-12-01T08:30:00Z',
//     assigned_to: 'John Doe',
//   },
//   {
//     id: 2,
//     title: 'Actualizar sitio web',
//     description: 'Revisar y actualizar el contenido de la página principal.',
//     completed: false,
//     priority: 'medium',
//     due_date: '2024-12-28T17:00:00Z',
//     created_at: '2024-12-02T09:15:00Z',
//     assigned_to: 'Jane Smith',
//   },
//   {
//     id: 3,
//     title: 'Reunión con el equipo de marketing',
//     description: 'Discutir estrategias para la próxima campaña.',
//     completed: true,
//     priority: 'low',
//     due_date: '2024-12-10T11:00:00Z',
//     created_at: '2024-12-05T10:00:00Z',
//     assigned_to: 'Emily White',
//   },
//   {
//     id: 4,
//     title: 'Revisar presupuesto anual',
//     description: 'Asegurarse de que todas las partidas estén correctamente asignadas.',
//     completed: false,
//     priority: 'high',
//     due_date: '2024-12-20T15:00:00Z',
//     created_at: '2024-12-10T13:45:00Z',
//     assigned_to: 'David Johnson',
//   },
//   {
//     id: 5,
//     title: 'Capacitación de nuevos empleados',
//     description: 'Organizar sesiones de capacitación para los recién ingresados.',
//     completed: true,
//     created_at: '2024-12-05T08:00:00Z',
//     assigned_to: 'Sarah Davis',
//   },
//   {
//     id: 6,
//     title: 'Configurar nuevo servidor',
//     description: 'Instalar y configurar un servidor para el entorno de producción.',
//     completed: false,
//     priority: 'medium',
//     due_date: '2024-12-30T18:00:00Z',
//     created_at: '2024-12-15T14:30:00Z',
//     assigned_to: 'Chris Lee',
//   },
//   {
//     id: 7,
//     title: 'Diseñar logotipo para cliente',
//     description: 'Crear un diseño inicial del logotipo solicitado por el cliente.',
//     completed: false,
//     priority: 'high',
//     due_date: '2024-12-25T09:00:00Z',
//     created_at: '2024-12-12T10:30:00Z',
//     assigned_to: 'Michael Brown',
//   },
//   {
//     id: 8,
//     title: 'Escribir artículo técnico',
//     description: 'Preparar un artículo técnico para el blog corporativo.',
//     completed: true,
//     priority: 'low',
//     created_at: '2024-12-01T11:00:00Z',
//     assigned_to: 'Emma Wilson',
//   },
// ];
